//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cloth.rc
//
#define IDRESTOREDEFAULTS               3
#define IDI_MAIN_ICON                   101
#define IDR_MAIN_ACCEL                  113
#define IDR_MENU                        141
#define IDR_POPUP                       142
#define IDD_SELECTDEVICE                144
#define IDD_SETTINGS                    146
#define IDC_DEVICE_COMBO                1000
#define IDC_ADAPTER_COMBO               1002
#define IDC_ADAPTERFORMAT_COMBO         1003
#define IDC_RESOLUTION_COMBO            1004
#define IDC_MULTISAMPLE_COMBO           1005
#define IDC_REFRESHRATE_COMBO           1006
#define IDC_BACKBUFFERFORMAT_COMBO      1007
#define IDC_DEPTHSTENCILBUFFERFORMAT_COMBO 1008
#define IDC_VERTEXPROCESSING_COMBO      1009
#define IDC_PRESENTINTERVAL_COMBO       1010
#define IDC_MULTISAMPLE_QUALITY_COMBO   1011
#define IDC_WINDOW                      1016
#define IDC_FULLSCREEN                  1018
#define IDC_EDITTIMESTEP                1027
#define IDC_EDITSTRETCHSPRING           1028
#define IDC_CHECKSHEAR                  1029
#define IDC_CHECKSTRETCH                1030
#define IDC_CHECKBEND                   1031
#define IDC_EDITSTRETCHDAMP             1032
#define IDC_EDITSHEARSPRING             1033
#define IDC_EDITSHEARDAMP               1034
#define IDC_EDITBENDSPRING              1035
#define IDC_EDITBENDDAMP                1036
#define IDC_EDITMASS                    1037
#define IDC_EDITGRAVITY                 1038
#define IDC_CHECKTOPLEFT                1039
#define IDC_CHECKBOTLEFT                1040
#define IDC_CHECKTOPRIGHT               1041
#define IDC_CHECKBOTRIGHT               1042
#define IDC_COMBOINTEGRATOR             1043
#define IDC_CHECKSELFCOLLISION          1044
#define IDC_CHECKWORLDCOLLISION         1045
#define IDC_EDITCLOTHSIZE               1046
#define IDM_CHANGEDEVICE                40002
#define IDM_TOGGLEFULLSCREEN            40003
#define IDM_EXIT                        40006
#define IDM_CONFIGINPUT                 40011
#define IDM_PAUSE                       40013
#define IDM_RESET                       40014
#define IDM_SETTINGS                    40015
#define IDM_RESETCAMERA                 40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
